### ISSUE TITLE
Preference Exploration Tool Demo does not contain anything.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/fluidproject.org#31]
## Describe the bug
When clicking on the Peference Exploration Tool Demo the link that is opening in the new tab it opens with a page that says error 404 page not found.

### To reproduce
1. Go to 'https://fluidproject.org/'
2. Click on 'View all projects '
3. Click on "Preference Exploration Tool Demo"

### Expected behavior
The link should redirect to a page that should contain some content related to it.

## Screenshots
![Screenshot from 2020-03-01 23-50-19](https://user-images.githubusercontent.com/55639487/75631420-c0b0bc80-5c18-11ea-958f-9699d901d2ab.png)

### Desktop
 - OS: [e.g. Ubuntu 18.04]
 - Browser [e.g. chrome]

**Comment by sachin10101998** [comment]
Already resolved in #14.

**Comment by abhinandansharma** [comment]
That PR is merged. If its already resolved then why am I still getting the 404 page.

**Comment by sachin10101998** [comment]
@abhinandansharma Needs `docpad run` on the server to build or update the 'out' folder.

**Comment by jobara** [comment]
@sachin10101998 and @abhinandansharma, that's correct, the site needs to be redeployed.
